alias: door openings west garage door suppress horn
# hide_entity: true
initial_state: true
trigger:
- platform: state
  entity_id: sensor.west_garage_overhead_door
  to: Violated
action:
  - service: timer.start
    entity_id: timer.driveway_horn_suppressed