alias: audio_visual living room tv off change input boolean
initial_state: true
trigger: 
  - entity_id: media_player.livingroomreceiver
    platform: state
    to: "off"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.living_room_media_power