alias: audio_visual media room tv on change input boolean
initial_state: true
trigger: 
  - entity_id: media_player.media_room_tv
    platform: state
    to: "off"
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.media_room_media_power