alias: audio_visual subwoofer switch off at 7
initial_state: true
trigger: 
  platform: time
  at: '19:00:00'
condition:
  condition: or
  conditions:
  - condition: state
    entity_id: light.livingroomsubwooferplug
    state: "on"
action:
  - service: light.turn_off
    data:
      entity_id: light.livingroomsubwooferplug