alias: system HACS update available
initial_state: true
trigger: 
  platform: state
  entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
  - condition: template
    value_template: "{{ (states(trigger.entity_id) | float) != 0}}"
action:
  - service: persistent_notification.create
    data_template:
      title: Updates pending in HACS
      message: >-
        {% for repo in state_attr(trigger.entity_id, 'repositories') %}
          **{{ repo.display_name }}** _{{ repo["installed version"] }}_ -> _{{ repo["available version"] }}_
        {% endfor %}
  - service: notify.dougemail
    data_template:
      title: HACS version update  
      message: A new version of HACS has been released and is awating download 
