homeassistant:
#  auth_providers:
#    - type: homeassistant
#     - type: trusted_networks
#      trusted_networks:
#        - 127.0.0.1
#        - ::1
#        - 192.168.0.0/24
  customize: !include customize.yaml
      
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#   base_url: https://ha.alishandoug.com

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_list automation/
#script: !include scripts.yaml
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml

updater:

logger:
  default: debug

sensor:
  # Weather prediction
  - platform: yr
  - platform: history_stats
    name: alisha home in last 10
    entity_id: person.alisha
    state: 'home'
    type: time
    end: '{{ now() }}'
    duration:
      minutes: 10
#  - platform: badnest
  - platform: moon
  - platform: template
    sensors:
      moon_phase:
        entity_id: sensor.moon
        friendly_name: 'Moon'
        value_template: '{{ states.sensor.moon.state }}'
        entity_picture_template: /local/moon_phases/{{ states.sensor.moon.state }}.png
#  - platform: template
#    sensors:
#      thermostat_setpoint:
#        entity_id: climate.hallway_thermostat
#        friendly_name: 'Thermostat Setpoint'
#        value_template: '{{ state_attr("climate.hallway_thermostat", "temperature") }}'
#  - platform: template
#    sensors:
#      thermostat_humidity:
#        entity_id: climate.hallway_thermostat
#        friendly_name: 'Humidity'
#        value_template: '{{ state_attr("climate.hallway_thermostat", "current_humidity") }}'
  - platform: darksky
    api_key: !secret DARKSKY_API_KEY
    units: ca
    forecast:
      - 1
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - temperature_min
      - temperature_max
      - temperature_low
      - temperature_high
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - wind_bearing
      - pressure
          
#badnest:
#  user_id: 12387017
#  access_token: !secret nest_access_token
#  region: ca

#climate:
#  - platform: badnest
#    scan_interval: 10


#nest:
#  client_id: !secret nest_client_id
#  client_secret: !secret nest_client_secret

#climate:
#  - platform: badnest
#    scan_interval: 10
      
elkm1:
  host: elk://192.168.1.82
  temperature_unit: C
  area:
   exclude:
    - 2-8
  counter:
   exclude:
    - 1-64
  keypad:
   exclude:
    - 3-16
  output:
   exclude: [1-2, 4-48, 53-208]
  zone:
   #include: [1-12, 17-19]
   include: [1-10, 17-19, 65-68]
  task:
   enabled: false
  thermostat:
   enabled: false
  plc:
   include:
    - 1-26
  setting:
   enabled: false


notify:
  - name: fileLog
    platform: file
    filename: customlog.txt
    timestamp: true
  - name: dougemail
    platform: smtp
    sender: !secret google_email
    recipient: !secret doug_email
    server: smtp.gmail.com
    starttls: 1
    port: 587
    timeout: 30
    username: !secret google_email
    password: !secret google_password
    sender_name: HomeAssistant
  - name: alishaemail
    platform: smtp
    sender: !secret google_email
    recipient: !secret alisha_email
    server: smtp.gmail.com
    starttls: 1
    port: 587
    timeout: 30
    username: !secret google_email
    password: !secret google_password
    sender_name: HomeAssistant
  - name: dougtext
    platform: smtp
    sender: !secret google_email
    recipient: !secret doug_text
    server: smtp.gmail.com
    starttls: 1
    port: 587
    timeout: 30
    username: !secret google_email
    password: !secret google_password
    sender_name: HomeAssistant
  - name: alishatext
    platform: smtp
    sender: !secret google_email
    recipient: !secret alisha_text
    server: smtp.gmail.com
    starttls: 1
    port: 587
    timeout: 30
    username: !secret google_email
    password: !secret google_password
    sender_name: HomeAssistant
  - platform: html5
    name: dougpush
    vapid_pub_key: !secret doug_push_key
    vapid_prv_key: !secret doug_push_prv_key
    vapid_email: !secret google_email
  - platform: html5
    name: alishapush
    vapid_pub_key: !secret alisha_push_key
    vapid_prv_key: !secret alisha_push_sender
    vapid_email: !secret alisha_email
  - name: loginfo
    platform: syslog
    
device_tracker:
  - platform: google_maps
    username: !secret google_email
  - platform: luci
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password
    new_device_defaults:
      track_new_devices: false
      
media_player:
  - platform: russound_rio
    host: 192.168.1.11
    name: Russound
  - platform: mpd
    host: 127.0.0.1
#  - platform: samsungtv
#    host: 192.168.1.81
#    port: 8001
#    name: LivingRoomSamsungTV
#    mac: f8:3f:51:34:ec:96
  - platform: onkyo
    host: 192.168.1.80
    name: LivingRoomReceiver
#  - platform: webostv
#    host: 192.168.1.85
#    name: Basement TV
#    timeout: 5
#    filename: .webostv.conf
#    turn_on_action:
#      service: wake_on_lan.send_magic_packet
#      data:
#        mac: "F0:86:20:02:7D:61"
  - platform: blackbird2
    host: 192.168.1.86
    ir_control: false
    zones:
      1:
        name: Living Room Matrix
      2:
        name: Gym Matrix
      3:
        name: Mechanical Room Matrix
      4:
        name: Media Room Matrix
      5:
        name: Computer Matrix
      6:
        name: Zone6 Matrix
      7:
        name: Zone7 Matrix
      8:
        name: Zone8 Matrix
    sources:
      1:
        name: PVR
      2:
        name: Computer
      3:
        name: Satellite
      4:
        name: ChromeCast
      5:
        name: Source5
      6:
        name: Source6
      7:
        name: Linux Computer
      8:
        name: DrivewayCamera

#blackbird2:
        
camera:
  - platform: onvif
    host: 192.168.1.93
    port: 80
    profile: 1
    name: front_door
    password: !secret camera_password
  - platform: onvif
    host: 192.168.1.96
    port: 80
    profile: 1
    name: mechanical
    password: !secret camera_password2
  - platform: onvif
    host: 192.168.1.94
    port: 80
    profile: 1
    name: garage
    password: !secret camera_password
#  - platform: doorbird
  
#doorbird:
#  devices:
#    - host: 192.168.1.95
#      username: !secret doorbird_username
#      password: !secret doorbird_password
#      token: !secret doorbird_token

timer:
  washer:
    duration: '00:05:00'
  dryer: 
    duration: '00:05:00'
  alarm: 
    duration: '00:04:00'
  driveway_horn_suppressed: 
    duration: '00:05:00'
  driveway_horn_suppressed_manual: 
    duration: '01:00:00'
  alarm_notification_repeat:
    duration: '00:01:00'
  porch_lights:
    duration: '00:10:00'
  christmas_lights:
    duration: '00:10:00'
    
remote:
  - platform: harmony
    name: Media Room
    host: 192.168.1.87

input_boolean:
  triggerstate:
    name: trigger state change
    initial: off
    icon: mdi:light-switch
  drivewayhorn:
    name: driveway horn
    initial: on
    icon: mdi:alert-decagram
  porchlightsonbyautomation:
    name: porch lights on by automation
    initial: off
    icon: mdi:lightbulb-on-outline
  porchlightsonbymanual:
    name: porch lights on by manual
    initial: off
    icon: mdi:lightbulb-on-outline
  christmaslightsonbyautomation:
    name: christmas lights on by automation
    initial: off
    icon: mdi:lightbulb-on
  christmaslightsonbymanual:
    name: christmas lights on by manual
    initial: off
    icon: mdi:lightbulb-on
  gym_media_power:
    name: Gym Media Power
  media_room_media_power:
    name: Media Room Media Power
  living_room_media_power:
    name: Living Room Media Power

    
input_text:
  last_page:
    name: Last Page Content
    initial: "None Since last Reboot"
  mykeycode:
    name: Last Key Code
    initial: "None Received"
  
input_datetime:
  last_page_time:
    name: Date/Time of last page
    has_date: true
    has_time: true
    
input_select:
  driveway_horn_suppression_time:
    name: Disable Horn for how long?
    initial: 00:05:00
    options:
      - 00:05:00
      - 00:30:00
      - 01:00:00
      - 03:00:00
      - 12:00:00
      
#google calendar
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
  
#Google Assistant
google_assistant: !include google_assistant.yaml

keyboard_remote:
  device_name: 'flirc.tv flirc Keyboard'
  type: 'key_down'
  
#ourgroceries:
#  username: !secret our_groceries_username
#  password: !secret our_groceries_password

