alias: laundry door opened
# hide_entity: true
initial_state: true
trigger: 
  platform: state
  entity_id: sensor.laundry_room_dr
condition:
  - condition: state
    entity_id: sensor.laundry_room_dr
    state: 'Violated'
action: 
  - service: timer.cancel
    entity_id: timer.washer
  - service: timer.cancel
    entity_id: timer.dryer