alias: alarm status changed
# hide_entity: true
initial_state: true
trigger:
  - entity_id: alarm_control_panel.area_001
    platform: state
action:
- service: notify.dougemail
  data_template:
    title: Alarm Status Changed to unhandled status {{ trigger.to_state.state }}
    message: Alarm Status Changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }} at {{now().strftime("%I:%M:%S-%Y/%m/%d")}}  
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != 'arming' }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != 'pending' }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != 'disarmed' }}"
    - condition: template
      value_template: "{{ trigger.to_state.state != 'armed_away' }}"
