alias: people alisha 5 min away
# hide_entity: true
initial_state: true
trigger:
- platform: state
  entity_id: person.alisha
  to: gerryglendas
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ is_state('entitiy_id: alisha_home_in_last_10','0.0')}}"
action:
  - service: script.speaktext
    data:
      message: "Alisha will be arriving at home in 5 minutes"