alias: lighting mirror front porch from east garage on
# hide_entity: true
initial_state: true
trigger:
  platform: state
  entity_id: light.garageeastexteriorlight
  to: "on"
action: 
  - service: light.turn_on
    entity_id: light.porchlights